tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "bat"
brew "entr"
brew "exa"
brew "fd"
brew "fish"
brew "fzf"
brew "git"
brew "git-delta"
brew "gnupg"
brew "htop"
brew "hub"
brew "imagesnap"
brew "jq"
brew "mas"
brew "neovim"
brew "openconnect"
brew "ripgrep"
brew "starship"
brew "stow"
brew "tealdeer"
brew "terminal-notifier"
brew "tig"
brew "tmux"
brew "volta"
brew "zoxide"
cask "ccleaner"
cask "docker"
cask "firefox"
cask "font-fira-code"
cask "google-chrome"
cask "iterm2"
cask "jumpcut"
cask "karabiner-elements"
cask "shiftit"
cask "sublime-text"
cask "vimr"
mas "1Password", id: 443987910
mas "Fantastical", id: 975937182
mas "Microsoft OneNote", id: 784801555
mas "Numbers", id: 409203825
mas "Octotree", id: 1457450145
mas "Things", id: 904280696
