tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "xwmx/taps"
brew "bat"
brew "python@3.9"
brew "glib"
brew "entr"
brew "exa"
brew "fd"
brew "guile"
brew "unbound"
brew "gnutls"
brew "gobject-introspection"
brew "harfbuzz"
brew "libass"
brew "srt"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "gcc"
brew "gh"
brew "git"
brew "git-delta"
brew "gnu-sed"
brew "gnupg"
brew "graphviz"
brew "htop"
brew "hub"
brew "icarus-verilog"
brew "imagesnap"
brew "jq"
brew "libproxy"
brew "lnav"
brew "lynx"
brew "mas"
brew "mkcert"
brew "mosh"
brew "neovim"
brew "nghttp2"
brew "nss"
brew "openconnect"
brew "pandoc"
brew "qt"
brew "poppler"
brew "pdfgrep"
brew "pinentry-mac"
brew "r"
brew "ruby-build"
brew "rbenv"
brew "ripgrep"
brew "shellcheck"
brew "starship"
brew "stow"
brew "tealdeer"
brew "terminal-notifier"
brew "tig"
brew "tmux"
brew "volta"
brew "wifi-password"
brew "xsv"
brew "yosys"
brew "youtube-dl"
brew "zoxide"
brew "xwmx/taps/nb"
cask "anki"
cask "bbedit"
cask "ccleaner"
cask "discord"
cask "docker"
cask "fawkes"
cask "firefox"
cask "font-fira-code"
cask "google-chrome"
cask "gpg-suite-no-mail"
cask "iterm2"
cask "jumpcut"
cask "karabiner-elements"
cask "microsoft-edge"
cask "microsoft-teams"
cask "miniforge"
cask "mumble"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklook-json"
cask "sequel-ace"
cask "shiftit"
cask "spark-ar-studio"
cask "spotify"
cask "sublime-text"
cask "tor-browser"
cask "tripmode"
cask "vimr"
cask "visual-studio-code"
cask "zettlr"
mas "1Password", id: 443987910
mas "Bear", id: 1091189122
mas "Fantastical", id: 975937182
mas "Microsoft Outlook", id: 985367838
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "StuffIt Expander", id: 919269455
mas "Things", id: 904280696
mas "Tweetbot", id: 1384080005
mas "WireGuard", id: 1451685025
